# Generated by Django 4.2 on 2024-11-09 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('monster_id', models.IntegerField(help_text='怪獸的唯一代號', primary_key=True, serialize=False)),
                ('monster_name', models.CharField(help_text='怪獸名稱', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(blank=True, help_text='用戶的暱稱', max_length=50, null=True)),
                ('coins', models.IntegerField(default=0, help_text='用戶的金幣')),
                ('gems', models.IntegerField(default=0, help_text='用戶的寶石數量')),
                ('photo', models.IntegerField(blank=True, help_text='用戶大頭貼的怪獸代號', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owners', to='user_profile.monster')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_monsters', to='user_profile.userprofile')),
            ],
        ),
    ]
