# Generated by Django 4.2 on 2024-11-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0, help_text='用戶的分數'),
        ),
    ]
