# Generated by Django 4.2 on 2024-11-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='name',
            new_name='monster_name',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='level',
        ),
    ]
