# Generated by Django 4.2.7 on 2024-11-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialReportSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
            options={
                "db_table": "財務報告摘要",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IncomeStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.BigIntegerField(db_column="代號", default=0)),
                ("name", models.CharField(db_column="名稱", default="", max_length=50)),
                (
                    "year_month",
                    models.CharField(db_column="年－月", default="", max_length=20),
                ),
                (
                    "net_operating_income",
                    models.DecimalField(
                        db_column="營業收入淨額", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "operating_expenses",
                    models.DecimalField(
                        db_column="營業費用", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "interest_income",
                    models.DecimalField(
                        db_column="利息收入", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "pre_tax_profit",
                    models.DecimalField(
                        db_column="稅前淨利", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "income_tax_expense",
                    models.DecimalField(
                        db_column="所得稅費用", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "consolidated_total_income",
                    models.DecimalField(
                        db_column="合併總損益", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "other_comprehensive_income",
                    models.DecimalField(
                        db_column="其他綜合損益－OCI",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "total_comprehensive_income",
                    models.DecimalField(
                        db_column="本期綜合損益總額", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "earnings_per_share",
                    models.DecimalField(
                        db_column="每股盈餘", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "weighted_average_shares",
                    models.DecimalField(
                        db_column="加權平均股數", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "special_dividends",
                    models.DecimalField(
                        db_column="發放特別股股息", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "continual_net_income_after_tax",
                    models.DecimalField(
                        db_column="常續性稅後淨利", decimal_places=2, default=0, max_digits=15
                    ),
                ),
            ],
            options={
                "db_table": "損益表",
                "managed": True,
                "unique_together": {("company_id", "year_month")},
            },
        ),
        migrations.CreateModel(
            name="FinancialIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.BigIntegerField(db_column="代號", default=0)),
                ("name", models.CharField(db_column="名稱", default="", max_length=50)),
                (
                    "year_month",
                    models.CharField(db_column="年－月", default="", max_length=20),
                ),
                (
                    "roa_after_tax_before_interest_a",
                    models.DecimalField(
                        db_column="ROA(A)稅後息前%",
                        decimal_places=5,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "roa_comprehensive",
                    models.DecimalField(
                        db_column="ROA－綜合損益", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "roe_after_tax_a",
                    models.DecimalField(
                        db_column="ROE(A)－稅後",
                        decimal_places=5,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "roe_continual_profit_b",
                    models.DecimalField(
                        db_column="ROE(B)－常續利益",
                        decimal_places=5,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "roe_comprehensive",
                    models.DecimalField(
                        db_column="ROE－綜合損益", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "continual_profit_rate_after_tax_a",
                    models.DecimalField(
                        db_column="常續利益率－稅後(A)",
                        decimal_places=5,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "net_profit_rate_after_tax_a",
                    models.DecimalField(
                        db_column="稅後淨利率(A)", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "continual_eps",
                    models.DecimalField(
                        db_column="常續性每股盈餘", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "revenue_growth_rate_a",
                    models.DecimalField(
                        db_column="營收成長率(A)", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "net_profit_growth_rate",
                    models.DecimalField(
                        db_column="稅後淨利成長率", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "operating_net_profit_growth_rate",
                    models.DecimalField(
                        db_column="經常淨利成長率", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "continual_net_profit_growth_rate",
                    models.DecimalField(
                        db_column="常續淨利成長率", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "total_assets_growth_rate",
                    models.DecimalField(
                        db_column="總資產成長率", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "net_worth_growth_rate",
                    models.DecimalField(
                        db_column="淨值成長率", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "total_liabilities_to_net_worth",
                    models.DecimalField(
                        db_column="總負債/總淨值", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "liabilities_rate",
                    models.DecimalField(
                        db_column="負債比率", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "net_worth_to_assets",
                    models.DecimalField(
                        db_column="淨值/資產", decimal_places=5, default=0, max_digits=10
                    ),
                ),
            ],
            options={
                "db_table": "指標",
                "managed": True,
                "unique_together": {("company_id", "year_month")},
            },
        ),
        migrations.CreateModel(
            name="CashFlowStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.BigIntegerField(db_column="代號", default=0)),
                ("name", models.CharField(db_column="名稱", default="", max_length=50)),
                (
                    "year_month",
                    models.CharField(db_column="年－月", default="", max_length=20),
                ),
                (
                    "pre_tax_net_profit_cfo",
                    models.DecimalField(
                        db_column="稅前淨利－CFO", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "depreciation_cfo",
                    models.DecimalField(
                        db_column="折舊－CFO", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "amortization_cfo",
                    models.DecimalField(
                        db_column="攤提－CFO", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "cash_flows_from_operations",
                    models.DecimalField(
                        db_column="來自營運之現金流量",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "new_investment_cfi",
                    models.DecimalField(
                        db_column="新增投資－CFI", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "investment_sale_cfi",
                    models.DecimalField(
                        db_column="出售投資－CFI", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "purchase_property_plant_equipment_cfi",
                    models.DecimalField(
                        db_column="購置不動產廠房設備－CFI",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "sale_property_plant_equipment_cfi",
                    models.DecimalField(
                        db_column="處分不動產廠房設備－CFI",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "cash_flows_from_investment",
                    models.DecimalField(
                        db_column="投資活動之現金流量",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "cash_increase_financing_cff",
                    models.DecimalField(
                        db_column="現金增（減）資－CFF",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "cash_dividends_cff",
                    models.DecimalField(
                        db_column="支付現金股利－CFF",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "cash_flows_from_financing",
                    models.DecimalField(
                        db_column="籌資活動之現金流量",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "foreign_exchange_effect",
                    models.DecimalField(
                        db_column="匯率影響數", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "cash_flows_for_period",
                    models.DecimalField(
                        db_column="本期產生現金流量", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "beginning_cash",
                    models.DecimalField(
                        db_column="期初現金及約當現金",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "ending_cash",
                    models.DecimalField(
                        db_column="期末現金及約當現金",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
            ],
            options={
                "db_table": "現金流量表",
                "managed": True,
                "unique_together": {("company_id", "year_month")},
            },
        ),
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.BigIntegerField(db_column="代號", default=0)),
                ("name", models.CharField(db_column="名稱", default="", max_length=50)),
                (
                    "year_month",
                    models.CharField(db_column="年－月", default="", max_length=20),
                ),
                (
                    "cash_and_equivalents",
                    models.DecimalField(
                        db_column="現金及約當現金", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "accounts_receivable",
                    models.DecimalField(
                        db_column="應收帳款及票據", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "other_receivables",
                    models.DecimalField(
                        db_column="其他應收款", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "property_plant_equipment",
                    models.DecimalField(
                        db_column="不動產廠房及設備", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "goodwill_and_intangibles",
                    models.DecimalField(
                        db_column="商譽及無形資產合計",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "right_of_use_assets",
                    models.DecimalField(
                        db_column="使用權資產", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "investment_property",
                    models.DecimalField(
                        db_column="投資性不動產淨額", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "other_non_current_assets",
                    models.DecimalField(
                        db_column="其他非流動資產", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        db_column="資產總額", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "accounts_payable",
                    models.DecimalField(
                        db_column="應付帳款及票據", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "other_payables",
                    models.DecimalField(
                        db_column="其他應付款", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "preferred_stock_liabilities",
                    models.DecimalField(
                        db_column="特別股負債－非流動",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "bonds_payable",
                    models.DecimalField(
                        db_column="應付公司債－非流動",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "other_long_term_loans",
                    models.DecimalField(
                        db_column="其他長期借款－非流動",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
                (
                    "lease_liabilities",
                    models.DecimalField(
                        db_column="租賃負債－非流動", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "provisions",
                    models.DecimalField(
                        db_column="負債準備－非流動", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "total_liabilities",
                    models.DecimalField(
                        db_column="負債總額", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "common_stock",
                    models.DecimalField(
                        db_column="普通股股本", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "preferred_stock",
                    models.DecimalField(
                        db_column="特別股股本", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "pre_received_stock_payments",
                    models.DecimalField(
                        db_column="預收股款", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "stock_dividends_payable",
                    models.DecimalField(
                        db_column="待分配股票股利", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "total_stock",
                    models.DecimalField(
                        db_column="股本", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "additional_paid_in_capital",
                    models.DecimalField(
                        db_column="資本公積合計", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "retained_earnings",
                    models.DecimalField(
                        db_column="保留盈餘", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "other_equity",
                    models.DecimalField(
                        db_column="其他權益", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "treasury_stock",
                    models.DecimalField(
                        db_column="庫藏股票帳面值", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "total_equity",
                    models.DecimalField(
                        db_column="股東權益總額", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "total_liabilities_and_equity",
                    models.DecimalField(
                        db_column="負債及股東權益總額",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                    ),
                ),
            ],
            options={
                "db_table": "資產負債表",
                "managed": True,
                "unique_together": {("company_id", "year_month")},
            },
        ),
    ]
