# Generated by Django 4.2 on 2024-10-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancesheet',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cashflowstatement',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='period',
            new_name='year_month',
        ),
        migrations.RenameField(
            model_name='cashflowstatement',
            old_name='period',
            new_name='year_month',
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='year_month',
            field=models.CharField(db_column='年－月', max_length=20),
        ),
        migrations.AlterModelTable(
            name='balancesheet',
            table='金控資產負債表',
        ),
        migrations.AlterModelTable(
            name='cashflowstatement',
            table='金控現金流量表',
        ),
        migrations.AlterModelTable(
            name='financialindicator',
            table='金控指標',
        ),
        migrations.AlterModelTable(
            name='incomestatement',
            table='金控損益表',
        ),
    ]
