# Generated by Django 4.2 on 2024-10-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_visualizer', '0002_alter_balancesheet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheet',
            name='capital_surplus',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='cash_and_cash_equivalents',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='dividends_distributable',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='investment_property_net',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='non_current_borrowings',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='non_current_lease_liabilities',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='non_current_liabilities_bonds',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='property_plant_and_equipment',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='provisions_non_current',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='received_in_advance_for_stock',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='special_stock',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='special_stock_liabilities_non_current',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='capital_increase_cff',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='cash_beginning',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='cash_ending',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='cash_flow_from_financing',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='cash_flow_from_investments',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='cash_flow_from_operations',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='code',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='net_cash_flow',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='profit_before_tax_cfo',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='property_disposal_cfi',
        ),
        migrations.RemoveField(
            model_name='cashflowstatement',
            name='purchase_property_cfi',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='consolidated_total_profit_loss',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='continuous_net_profit_after_tax',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='net_revenue',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='operating_expense',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='other_comprehensive_income_oci',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='special_stock_dividend',
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='additional_paid_in_capital',
            field=models.DecimalField(db_column='資本公積合計', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='bonds_payable',
            field=models.DecimalField(db_column='應付公司債－非流動', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='cash_and_equivalents',
            field=models.DecimalField(db_column='現金及約當現金', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='company_id',
            field=models.BigIntegerField(db_column='代號', default=0),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='investment_property',
            field=models.DecimalField(db_column='投資性不動產淨額', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='lease_liabilities',
            field=models.DecimalField(db_column='租賃負債－非流動', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='other_long_term_loans',
            field=models.DecimalField(db_column='其他長期借款－非流動', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='pre_received_stock_payments',
            field=models.DecimalField(db_column='預收股款', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='preferred_stock',
            field=models.DecimalField(db_column='特別股股本', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='preferred_stock_liabilities',
            field=models.DecimalField(db_column='特別股負債－非流動', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='property_plant_equipment',
            field=models.DecimalField(db_column='不動產廠房及設備', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='provisions',
            field=models.DecimalField(db_column='負債準備－非流動', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='stock_dividends_payable',
            field=models.DecimalField(db_column='待分配股票股利', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='total_stock',
            field=models.DecimalField(db_column='股本', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='beginning_cash',
            field=models.DecimalField(db_column='期初現金及約當現金', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='cash_flows_for_period',
            field=models.DecimalField(db_column='本期產生現金流量', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='cash_flows_from_financing',
            field=models.DecimalField(db_column='籌資活動之現金流量', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='cash_flows_from_investment',
            field=models.DecimalField(db_column='投資活動之現金流量', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='cash_flows_from_operations',
            field=models.DecimalField(db_column='來自營運之現金流量', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='cash_increase_financing_cff',
            field=models.DecimalField(db_column='現金增（減）資－CFF', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='company_id',
            field=models.BigIntegerField(db_column='代號', default=0),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='ending_cash',
            field=models.DecimalField(db_column='期末現金及約當現金', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='pre_tax_net_profit_cfo',
            field=models.DecimalField(db_column='稅前淨利－CFO', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='purchase_property_plant_equipment_cfi',
            field=models.DecimalField(db_column='購置不動產廠房設備－CFI', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='sale_property_plant_equipment_cfi',
            field=models.DecimalField(db_column='處分不動產廠房設備－CFI', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='consolidated_total_income',
            field=models.DecimalField(db_column='合併總損益', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='continual_net_income_after_tax',
            field=models.DecimalField(db_column='常續性稅後淨利', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='net_operating_income',
            field=models.DecimalField(db_column='營業收入淨額', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='operating_expenses',
            field=models.DecimalField(db_column='營業費用', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='other_comprehensive_income',
            field=models.DecimalField(db_column='其他綜合損益－OCI', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='special_dividends',
            field=models.DecimalField(db_column='發放特別股股息', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='accounts_payable',
            field=models.DecimalField(db_column='應付帳款及票據', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='accounts_receivable',
            field=models.DecimalField(db_column='應收帳款及票據', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='common_stock',
            field=models.DecimalField(db_column='普通股股本', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='goodwill_and_intangibles',
            field=models.DecimalField(db_column='商譽及無形資產合計', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='name',
            field=models.CharField(db_column='名稱', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_equity',
            field=models.DecimalField(db_column='其他權益', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_non_current_assets',
            field=models.DecimalField(db_column='其他非流動資產', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_payables',
            field=models.DecimalField(db_column='其他應付款', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_receivables',
            field=models.DecimalField(db_column='其他應收款', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='retained_earnings',
            field=models.DecimalField(db_column='保留盈餘', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='right_of_use_assets',
            field=models.DecimalField(db_column='使用權資產', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_assets',
            field=models.DecimalField(db_column='資產總額', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_equity',
            field=models.DecimalField(db_column='股東權益總額', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_liabilities',
            field=models.DecimalField(db_column='負債總額', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_liabilities_and_equity',
            field=models.DecimalField(db_column='負債及股東權益總額', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='treasury_stock',
            field=models.DecimalField(db_column='庫藏股票帳面值', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='year_month',
            field=models.CharField(db_column='年－月', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashflowstatement',
            name='amortization_cfo',
            field=models.DecimalField(db_column='攤提－CFO', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashflowstatement',
            name='cash_dividends_cff',
            field=models.DecimalField(db_column='支付現金股利－CFF', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashflowstatement',
            name='depreciation_cfo',
            field=models.DecimalField(db_column='折舊－CFO', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashflowstatement',
            name='foreign_exchange_effect',
            field=models.DecimalField(db_column='匯率影響數', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashflowstatement',
            name='investment_sale_cfi',
            field=models.DecimalField(db_column='出售投資－CFI', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashflowstatement',
            name='name',
            field=models.CharField(db_column='名稱', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cashflowstatement',
            name='new_investment_cfi',
            field=models.DecimalField(db_column='新增投資－CFI', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashflowstatement',
            name='year_month',
            field=models.CharField(db_column='年－月', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='company_id',
            field=models.BigIntegerField(db_column='代號', default=0),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='continual_eps',
            field=models.DecimalField(db_column='常續性每股盈餘', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='continual_net_profit_growth_rate',
            field=models.DecimalField(db_column='常續淨利成長率', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='continual_profit_rate_after_tax_a',
            field=models.DecimalField(db_column='常續利益率－稅後(A)', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='liabilities_rate',
            field=models.DecimalField(db_column='負債比率', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='name',
            field=models.CharField(db_column='名稱', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='net_profit_growth_rate',
            field=models.DecimalField(db_column='稅後淨利成長率', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='net_profit_rate_after_tax_a',
            field=models.DecimalField(db_column='稅後淨利率(A)', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='net_worth_growth_rate',
            field=models.DecimalField(db_column='淨值成長率', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='net_worth_to_assets',
            field=models.DecimalField(db_column='淨值/資產', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='operating_net_profit_growth_rate',
            field=models.DecimalField(db_column='經常淨利成長率', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='revenue_growth_rate_a',
            field=models.DecimalField(db_column='營收成長率(A)', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='roa_after_tax_before_interest_a',
            field=models.DecimalField(db_column='ROA(A)稅後息前%', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='roa_comprehensive',
            field=models.DecimalField(db_column='ROA－綜合損益', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='roe_after_tax_a',
            field=models.DecimalField(db_column='ROE(A)－稅後', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='roe_comprehensive',
            field=models.DecimalField(db_column='ROE－綜合損益', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='roe_continual_profit_b',
            field=models.DecimalField(db_column='ROE(B)－常續利益', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='total_assets_growth_rate',
            field=models.DecimalField(db_column='總資產成長率', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='total_liabilities_to_net_worth',
            field=models.DecimalField(db_column='總負債/總淨值', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='year_month',
            field=models.CharField(db_column='年－月', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='company_id',
            field=models.BigIntegerField(db_column='代號', default=0),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='earnings_per_share',
            field=models.DecimalField(db_column='每股盈餘', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='income_tax_expense',
            field=models.DecimalField(db_column='所得稅費用', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='interest_income',
            field=models.DecimalField(db_column='利息收入', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='name',
            field=models.CharField(db_column='名稱', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='pre_tax_profit',
            field=models.DecimalField(db_column='稅前淨利', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='total_comprehensive_income',
            field=models.DecimalField(db_column='本期綜合損益總額', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='weighted_average_shares',
            field=models.DecimalField(db_column='加權平均股數', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='year_month',
            field=models.CharField(db_column='年－月', default='', max_length=20),
        ),
        migrations.AlterModelTable(
            name='balancesheet',
            table='資產負債表',
        ),
        migrations.AlterModelTable(
            name='cashflowstatement',
            table='現金流量表',
        ),
        migrations.AlterModelTable(
            name='financialindicator',
            table='指標',
        ),
        migrations.AlterModelTable(
            name='incomestatement',
            table='損益表',
        ),
    ]
