# Generated by Django 4.2 on 2024-11-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_visualizer', '0003_remove_balancesheet_capital_surplus_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together={('company_id', 'year_month')},
        ),
        migrations.AlterUniqueTogether(
            name='cashflowstatement',
            unique_together={('company_id', 'year_month')},
        ),
        migrations.AlterUniqueTogether(
            name='financialindicator',
            unique_together={('company_id', 'year_month')},
        ),
        migrations.AlterUniqueTogether(
            name='incomestatement',
            unique_together={('company_id', 'year_month')},
        ),
    ]
