# Generated by Django 4.2.7 on 2024-11-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicsQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("options", models.JSONField()),
                ("difficulty", models.CharField(max_length=1)),
                ("type", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "basics_questions",
            },
        ),
        migrations.CreateModel(
            name="NewsQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("question", models.TextField()),
                ("options", models.JSONField()),
                ("difficulty", models.CharField(max_length=1)),
                ("source", models.TextField()),
                ("url", models.URLField()),
            ],
            options={
                "db_table": "news_questions",
            },
        ),
    ]
